### ISSUE TITLE
Provisioning Fails

### ISSUE THREAD

**Issue by XedinUnknown** [forkriver/WPDistillery#2]
When the box provisions for the first time, I get the following as part of the output:

```
    default: »»» installing WordPress Multisite...
    default: PHP Fatal error:  Uncaught Error: Call to undefined function apply_filters() in /var/www/public/wp-includes/load.php:316
    default: Stack trace:
    default: #0 phar:///usr/local/bin/wp/php/utils-wp.php(22): wp_debug_mode()
    default: #1 phar:///usr/local/bin/wp/php/wp-settings-cli.php(52): WP_CLI\Utils\wp_debug_mode()
    default: #2 phar:///usr/local/bin/wp/php/wp-cli.php(26): require('phar:///usr/loc...')
    default: #3 phar:///usr/local/bin/wp/php/boot-phar.php(5): include('phar:///usr/loc...')
    default: #4 /usr/local/bin/wp(4): include('phar:///usr/loc...')
    default: #5 {main}
    default:   thrown in /var/www/public/wp-includes/load.php on line 316
    default: »»» aborting WPDistillery setup!
```

The website is available at the correct URL, but offers to go through the 5-minute installation.

**Comment by pjohanneson** [comment]
I see you found [this solution](https://github.com/flurinduerst/WPDistillery/issues/91) in the parent project. Does this solve the issue you raised here? If so, I'll close it.

**Comment by XedinUnknown** [comment]
Hi, and thanks for the quick response!

That's not really a solution for this problem, but just a general way to use your fork.
